### ISSUE TITLE
Cannot compile with GHC 8.10.3 under Windows

### ISSUE THREAD

**Issue by PaulJohnson** [gtk2hs/svgcairo#9]
Lots of error messages about incorrect types in .h files. The following is a short extract from `stack build`

    svgcairo                         > C:/Users/Paul Johnson/AppData/Local/Programs/stack/x86_64-windows/ghc-8.10.3/mingw/lib/gcc/x86_64-w64-mingw32/9.2.0/include/xopintrin.h:606:45: note: expected '__vector(8) short int' but argument is of type 'short int'
    svgcairo                         > C:/Users/Paul Johnson/AppData/Local/Programs/stack/x86_64-windows/ghc-8.10.3/mingw/lib/gcc/x86_64-w64-mingw32/9.2.0/include/xopintrin.h:606:58: error: incompatible type for argument 2 of '__builtin_ia32_vpcomgew'
    svgcairo                         >   606 |   return (__m128i) __builtin_ia32_vpcomgew ((__v8hi)__A, (__v8hi)__B);
    svgcairo                         >       |                                                          ^~~~~~~~~~~
    svgcairo                         >       |                                                          |
    svgcairo                         >       |                                                          short int
    svgcairo                         > C:/Users/Paul Johnson/AppData/Local/Programs/stack/x86_64-windows/ghc-8.10.3/mingw/lib/gcc/x86_64-w64-mingw32/9.2.0/include/xopintrin.h:606:58: note: expected '__vector(8) short int' but argument is of type 'short int'

**Comment by PaulJohnson** [comment]
Also GHC 8.10.4
